on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
          changelog-types: |
            [
              {"type":"feat","section":"🚀 Features","hidden":false},
              {"type":"fix","section":"🐛 Bug Fixes","hidden":false},
              {"type":"perf","section":"↗️ Performance Improvements","hidden":false},
              {"type":"revert","section":"🔙 Reverts","hidden":false},
              {"type":"docs","section":"📖 Documentation","hidden":false},
              {"type":"style","section":"💅 Styles","hidden":false},
              {"type":"chore","section":"🧹 Chores","hidden":true},
              {"type":"refactor","section":"🛠 Refactorings","hidden":false},
              {"type":"test","section":"✅ Tests","hidden":false},
              {"type":"build","section":"📦 Build System & Dependencies","hidden":false},
              {"type":"ci","section":"🔄 CI/CD","hidden":true}
            ]
